# Permalinks
permalink:        /post/:title
relative_permalinks: true

# Setup
title:            Laravel Indonesia
tagline:          Tutorial Laravel Bahasa Indonesia
url:              http://id-laravel.com
paginate:         1
baseurl:          /
author:
  name:           Bayu Hendra Winata
  url:            https://twitter.com/uyab
  email:          uyab.exe@gmail.com

# Build options
exclude:          [node_modules]

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/id-laravel/id-laravel.github.io
